import { ThemeToggler } from "@/components";
import "@gravity-ui/uikit/styles/styles.css";
import type { Metadata } from "next";
import { ReactNode } from "react";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <ThemeToggler>{children}</ThemeToggler>
      </body>
    </html>
  );
}
